# Generated by Django 3.2.7 on 2023-11-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponibilite', models.PositiveIntegerField()),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etat', models.CharField(default="Non diffusé aujourd'hui", max_length=30)),
                ('titre', models.CharField(max_length=30)),
                ('auteur', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('synopsis', models.CharField(default='Pas de synopsis disponible', max_length=1000)),
                ('affiche', models.CharField(max_length=200)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.room')),
            ],
        ),
    ]
